function out = computeZeroReynolds(k, cotbeta, S, AD, AT, AB, AK, AI)
    %COMPUTE_ZERO_REYNOLDS Given required parameters, returns eigenvalue c
    %from the zero Reynolds number analysis
    if (AI == 0)
        out =  [-(8*I*ab*K^7*EXP(2*K) + 2*i*AB*k^5*exp(4*k) + 4*i*AB*k^5*exp(2*k)...
            + 2*i*AB*k^5 - 4*i*AD*S*k^3*exp(2*k) + i*AD*S*k^2*exp(4*k) - ...
            i*AD*S*k^2 - 8*i*AD*cotbeta*k*exp(2*k) + 2*i*AD*cotbeta*exp(4*k) - ...
            2*i*AD*cotbeta - 8*AD*k^4*exp(2*k) - 2*AD*k^2*exp(4*k) - ...
            12*AD*k^2*exp(2*k) - 2*AD*k^2 + 8*i*AK*k^3*exp(2*k) + ...
            2*i*AK*k*exp(4*k) + 4*i*AK*k*exp(2*k) + 2*i*AK*k + ...
            8*i*AT*k^5*exp(2*k) + 2*i*AT*k^3*exp(4*k) + 4*i*AT*k^3*exp(2*k) + ...
            2*i*AT*k^3 + 2*i*S*k^3*exp(4*k) + 4*i*S*k^3*exp(2*k) + 2*i*S*k^3 - ...
            16*i*cotbeta*k^3*exp(2*k) + 16*k^4*exp(2*k) - 4*k^3*exp(4*k) + ...
            4*k^3 - 8*k^2*exp(4*k) - 8*k^2 - i*sqrt(64*AB^2*k^14*exp(4*k) + ...
            32*AB^2*k^12*exp(6*k) + 64*AB^2*k^12*exp(4*k) + ...
            32*AB^2*k^12*exp(2*k) + 4*AB^2*k^10*exp(8*k) + ...
            16*AB^2*k^10*exp(6*k) + 24*AB^2*k^10*exp(4*k) + ...
            16*AB^2*k^10*exp(2*k) + 4*AB^2*k^10 + 64*AB*AD*S*k^10*exp(4*k) - ...
            16*AB*AD*S*k^9*exp(6*k) + 16*AB*AD*S*k^9*exp(2*k) + ...
            16*AB*AD*S*k^8*exp(6*k) + 32*AB*AD*S*k^8*exp(4*k) + ...
            16*AB*AD*S*k^8*exp(2*k) - 4*AB*AD*S*k^7*exp(8*k) - ...
            8*AB*AD*S*k^7*exp(6*k) + 8*AB*AD*S*k^7*exp(2*k) + 4*AB*AD*S*k^7 + ...
            128*AB*AD*cotbeta*k^8*exp(4*k) - 32*AB*AD*cotbeta*k^7*exp(6*k) + ...
            32*AB*AD*cotbeta*k^7*exp(2*k) + 32*AB*AD*cotbeta*k^6*exp(6*k) + ...
            64*AB*AD*cotbeta*k^6*exp(4*k) + 32*AB*AD*cotbeta*k^6*exp(2*k) - ...
            8*AB*AD*cotbeta*k^5*exp(8*k) - 16*AB*AD*cotbeta*k^5*exp(6*k) + ...
            16*AB*AD*cotbeta*k^5*exp(2*k) + 8*AB*AD*cotbeta*k^5 - ...
            128*i*AB*AD*k^11*exp(4*k) - 64*i*AB*AD*k^9*exp(6*k) - ...
            256*i*AB*AD*k^9*exp(4*k) - 64*i*AB*AD*k^9*exp(2*k) - ...
            8*i*AB*AD*k^7*exp(8*k) - 64*i*AB*AD*k^7*exp(6*k) - ...
            112*i*AB*AD*k^7*exp(4*k) - 64*i*AB*AD*k^7*exp(2*k) - 8*i*AB*AD*k^7 ...
            + 128*AB*AK*k^10*exp(4*k) + 64*AB*AK*k^8*exp(6*k) + ...
            128*AB*AK*k^8*exp(4*k) + 64*AB*AK*k^8*exp(2*k) + ...
            8*AB*AK*k^6*exp(8*k) + 32*AB*AK*k^6*exp(6*k) + ...
            48*AB*AK*k^6*exp(4*k) + 32*AB*AK*k^6*exp(2*k) + 8*AB*AK*k^6 + ...
            128*AB*AT*k^12*exp(4*k) + 64*AB*AT*k^10*exp(6*k) + ...
            128*AB*AT*k^10*exp(4*k) + 64*AB*AT*k^10*exp(2*k) + ...
            8*AB*AT*k^8*exp(8*k) + 32*AB*AT*k^8*exp(6*k) + ...
            48*AB*AT*k^8*exp(4*k) + 32*AB*AT*k^8*exp(2*k) + 8*AB*AT*k^8 + ...
            32*AB*S*k^10*exp(6*k) - 192*AB*S*k^10*exp(4*k) + ...
            32*AB*S*k^10*exp(2*k) + 128*AB*S*k^9*exp(6*k) - ...
            128*AB*S*k^9*exp(2*k) - 8*AB*S*k^8*exp(8*k) + 32*AB*S*k^8*exp(6*k) ...
            + 80*AB*S*k^8*exp(4*k) + 32*AB*S*k^8*exp(2*k) - 8*AB*S*k^8 - ...
            256*AB*cotbeta*k^10*exp(4*k) - 64*AB*cotbeta*k^8*exp(6*k) - ...
            640*AB*cotbeta*k^8*exp(4*k) - 64*AB*cotbeta*k^8*exp(2*k) + ...
            256*AB*cotbeta*k^7*exp(6*k) - 256*AB*cotbeta*k^7*exp(2*k) - ...
            32*AB*cotbeta*k^6*exp(8*k) + 64*AB*cotbeta*k^6*exp(4*k) - ...
            32*AB*cotbeta*k^6 + 256*i*AB*k^11*exp(4*k) - 64*i*AB*k^10*exp(6*k) ...
            + 64*i*AB*k^10*exp(2*k) + 192*i*AB*k^9*exp(6*k) + ...
            640*i*AB*k^9*exp(4*k) + 192*i*AB*k^9*exp(2*k) - ...
            16*i*AB*k^8*exp(8*k) - 160*i*AB*k^8*exp(6*k) + ...
            160*i*AB*k^8*exp(2*k) + 16*i*AB*k^8 + 32*i*AB*k^7*exp(8*k) + ...
            64*i*AB*k^7*exp(6*k) + 64*i*AB*k^7*exp(4*k) + 64*i*AB*k^7*exp(2*k) ...
            + 32*i*AB*k^7 + 16*AD^2*S^2*k^6*exp(4*k) - 8*AD^2*S^2*k^5*exp(6*k) ...
            + 8*AD^2*S^2*k^5*exp(2*k) + AD^2*S^2*k^4*exp(8*k) - ...
            2*AD^2*S^2*k^4*exp(4*k) + AD^2*S^2*k^4 + ...
            64*AD^2*S*cotbeta*k^4*exp(4*k) - 32*AD^2*S*cotbeta*k^3*exp(6*k) + ...
            32*AD^2*S*cotbeta*k^3*exp(2*k) + 4*AD^2*S*cotbeta*k^2*exp(8*k) - ...
            8*AD^2*S*cotbeta*k^2*exp(4*k) + 4*AD^2*S*cotbeta*k^2 - ...
            64*i*AD^2*S*k^7*exp(4*k) + 16*i*AD^2*S*k^6*exp(6*k) - ...
            16*i*AD^2*S*k^6*exp(2*k) - 16*i*AD^2*S*k^5*exp(6*k) - ...
            96*i*AD^2*S*k^5*exp(4*k) - 16*i*AD^2*S*k^5*exp(2*k) + ...
            4*i*AD^2*S*k^4*exp(8*k) + 24*i*AD^2*S*k^4*exp(6*k) - ...
            24*i*AD^2*S*k^4*exp(2*k) - 4*i*AD^2*S*k^4 + ...
            64*AD^2*cotbeta^2*k^2*exp(4*k) - 32*AD^2*cotbeta^2*k*exp(6*k) + ...
            32*AD^2*cotbeta^2*k*exp(2*k) + 4*AD^2*cotbeta^2*exp(8*k) - ...
            8*AD^2*cotbeta^2*exp(4*k) + 4*AD^2*cotbeta^2 - ...
            128*i*AD^2*cotbeta*k^5*exp(4*k) + 32*i*AD^2*cotbeta*k^4*exp(6*k) - ...
            32*i*AD^2*cotbeta*k^4*exp(2*k) - 32*i*AD^2*cotbeta*k^3*exp(6*k) - ...
            192*i*AD^2*cotbeta*k^3*exp(4*k) - 32*i*AD^2*cotbeta*k^3*exp(2*k) + ...
            8*i*AD^2*cotbeta*k^2*exp(8*k) + 48*i*AD^2*cotbeta*k^2*exp(6*k) - ...
            48*i*AD^2*cotbeta*k^2*exp(2*k) - 8*i*AD^2*cotbeta*k^2 - ...
            64*AD^2*k^8*exp(4*k) - 32*AD^2*k^6*exp(6*k) - ...
            192*AD^2*k^6*exp(4*k) - 32*AD^2*k^6*exp(2*k) - 4*AD^2*k^4*exp(8*k) ...
            - 48*AD^2*k^4*exp(6*k) - 152*AD^2*k^4*exp(4*k) - ...
            48*AD^2*k^4*exp(2*k) - 4*AD^2*k^4 + 64*AD*AK*S*k^6*exp(4*k) - ...
            16*AD*AK*S*k^5*exp(6*k) + 16*AD*AK*S*k^5*exp(2*k) + ...
            16*AD*AK*S*k^4*exp(6*k) + 32*AD*AK*S*k^4*exp(4*k) + ...
            16*AD*AK*S*k^4*exp(2*k) - 4*AD*AK*S*k^3*exp(8*k) - ...
            8*AD*AK*S*k^3*exp(6*k) + 8*AD*AK*S*k^3*exp(2*k) + 4*AD*AK*S*k^3 + ...
            128*AD*AK*cotbeta*k^4*exp(4*k) - 32*AD*AK*cotbeta*k^3*exp(6*k) + ...
            32*AD*AK*cotbeta*k^3*exp(2*k) + 32*AD*AK*cotbeta*k^2*exp(6*k) + ...
            64*AD*AK*cotbeta*k^2*exp(4*k) + 32*AD*AK*cotbeta*k^2*exp(2*k) - ...
            8*AD*AK*cotbeta*k*exp(8*k) - 16*AD*AK*cotbeta*k*exp(6*k) + ...
            16*AD*AK*cotbeta*k*exp(2*k) + 8*AD*AK*cotbeta*k - ...
            128*i*AD*AK*k^7*exp(4*k) - 64*i*AD*AK*k^5*exp(6*k) - ...
            256*i*AD*AK*k^5*exp(4*k) - 64*i*AD*AK*k^5*exp(2*k) - ...
            8*i*AD*AK*k^3*exp(8*k) - 64*i*AD*AK*k^3*exp(6*k) - ...
            112*i*AD*AK*k^3*exp(4*k) - 64*i*AD*AK*k^3*exp(2*k) - 8*i*AD*AK*k^3 ...
            + 64*AD*AT*S*k^8*exp(4*k) - 16*AD*AT*S*k^7*exp(6*k) + ...
            16*AD*AT*S*k^7*exp(2*k) + 16*AD*AT*S*k^6*exp(6*k) + ...
            32*AD*AT*S*k^6*exp(4*k) + 16*AD*AT*S*k^6*exp(2*k) - ...
            4*AD*AT*S*k^5*exp(8*k) - 8*AD*AT*S*k^5*exp(6*k) + ...
            8*AD*AT*S*k^5*exp(2*k) + 4*AD*AT*S*k^5 + ...
            128*AD*AT*cotbeta*k^6*exp(4*k) - 32*AD*AT*cotbeta*k^5*exp(6*k) + ...
            32*AD*AT*cotbeta*k^5*exp(2*k) + 32*AD*AT*cotbeta*k^4*exp(6*k) + ...
            64*AD*AT*cotbeta*k^4*exp(4*k) + 32*AD*AT*cotbeta*k^4*exp(2*k) - ...
            8*AD*AT*cotbeta*k^3*exp(8*k) - 16*AD*AT*cotbeta*k^3*exp(6*k) + ...
            16*AD*AT*cotbeta*k^3*exp(2*k) + 8*AD*AT*cotbeta*k^3 - ...
            128*i*AD*AT*k^9*exp(4*k) - 64*i*AD*AT*k^7*exp(6*k) - ...
            256*i*AD*AT*k^7*exp(4*k) - 64*i*AD*AT*k^7*exp(2*k) - ...
            8*i*AD*AT*k^5*exp(8*k) - 64*i*AD*AT*k^5*exp(6*k) - ...
            112*i*AD*AT*k^5*exp(4*k) - 64*i*AD*AT*k^5*exp(2*k) - 8*i*AD*AT*k^5 ...
            - 16*AD*S^2*k^6*exp(6*k) - 32*AD*S^2*k^6*exp(4*k) - ...
            16*AD*S^2*k^6*exp(2*k) + 4*AD*S^2*k^5*exp(8*k) + ...
            8*AD*S^2*k^5*exp(6*k) - 8*AD*S^2*k^5*exp(2*k) - 4*AD*S^2*k^5 - ...
            128*AD*S*cotbeta*k^6*exp(4*k) + 32*AD*S*cotbeta*k^5*exp(6*k) - ...
            32*AD*S*cotbeta*k^5*exp(2*k) - 96*AD*S*cotbeta*k^4*exp(6*k) - ...
            192*AD*S*cotbeta*k^4*exp(4*k) - 96*AD*S*cotbeta*k^4*exp(2*k) + ...
            24*AD*S*cotbeta*k^3*exp(8*k) + 48*AD*S*cotbeta*k^3*exp(6*k) - ...
            48*AD*S*cotbeta*k^3*exp(2*k) - 24*AD*S*cotbeta*k^3 + ...
            32*i*AD*S*k^7*exp(6*k) + 192*i*AD*S*k^7*exp(4*k) + ...
            32*i*AD*S*k^7*exp(2*k) - 192*i*AD*S*k^6*exp(6*k) + ...
            192*i*AD*S*k^6*exp(2*k) + 16*i*AD*S*k^5*exp(8*k) + ...
            96*i*AD*S*k^5*exp(4*k) + 16*i*AD*S*k^5 - 16*i*AD*S*k^4*exp(8*k) - ...
            64*i*AD*S*k^4*exp(6*k) + 64*i*AD*S*k^4*exp(2*k) + 16*i*AD*S*k^4 - ...
            256*AD*cotbeta^2*k^4*exp(4*k) + 64*AD*cotbeta^2*k^3*exp(6*k) - ...
            64*AD*cotbeta^2*k^3*exp(2*k) - 128*AD*cotbeta^2*k^2*exp(6*k) - ...
            256*AD*cotbeta^2*k^2*exp(4*k) - 128*AD*cotbeta^2*k^2*exp(2*k) + ...
            32*AD*cotbeta^2*k*exp(8*k) + 64*AD*cotbeta^2*k*exp(6*k) - ...
            64*AD*cotbeta^2*k*exp(2*k) - 32*AD*cotbeta^2*k + ...
            256*i*AD*cotbeta*k^7*exp(4*k) + 192*i*AD*cotbeta*k^5*exp(6*k) + ...
            896*i*AD*cotbeta*k^5*exp(4*k) + 192*i*AD*cotbeta*k^5*exp(2*k) - ...
            384*i*AD*cotbeta*k^4*exp(6*k) + 384*i*AD*cotbeta*k^4*exp(2*k) + ...
            48*i*AD*cotbeta*k^3*exp(8*k) + 128*i*AD*cotbeta*k^3*exp(6*k) + ...
            416*i*AD*cotbeta*k^3*exp(4*k) + 128*i*AD*cotbeta*k^3*exp(2*k) + ...
            48*i*AD*cotbeta*k^3 - 32*i*AD*cotbeta*k^2*exp(8*k) - ...
            128*i*AD*cotbeta*k^2*exp(6*k) + 128*i*AD*cotbeta*k^2*exp(2*k) + ...
            32*i*AD*cotbeta*k^2 + 256*AD*k^8*exp(4*k) - 64*AD*k^7*exp(6*k) + ...
            64*AD*k^7*exp(2*k) + 192*AD*k^6*exp(6*k) + 896*AD*k^6*exp(4*k) + ...
            192*AD*k^6*exp(2*k) - 16*AD*k^5*exp(8*k) - 96*AD*k^5*exp(6*k) + ...
            96*AD*k^5*exp(2*k) + 16*AD*k^5 + 32*AD*k^4*exp(8*k) + ...
            64*AD*k^4*exp(6*k) + 320*AD*k^4*exp(4*k) + 64*AD*k^4*exp(2*k) + ...
            32*AD*k^4 + 64*AK^2*k^6*exp(4*k) + 32*AK^2*k^4*exp(6*k) + ...
            64*AK^2*k^4*exp(4*k) + 32*AK^2*k^4*exp(2*k) + 4*AK^2*k^2*exp(8*k) ...
            + 16*AK^2*k^2*exp(6*k) + 24*AK^2*k^2*exp(4*k) + ...
            16*AK^2*k^2*exp(2*k) + 4*AK^2*k^2 + 128*AK*AT*k^8*exp(4*k) + ...
            64*AK*AT*k^6*exp(6*k) + 128*AK*AT*k^6*exp(4*k) + ...
            64*AK*AT*k^6*exp(2*k) + 8*AK*AT*k^4*exp(8*k) + ...
            32*AK*AT*k^4*exp(6*k) + 48*AK*AT*k^4*exp(4*k) + ...
            32*AK*AT*k^4*exp(2*k) + 8*AK*AT*k^4 + 32*AK*S*k^6*exp(6*k) - ...
            192*AK*S*k^6*exp(4*k) + 32*AK*S*k^6*exp(2*k) + ...
            128*AK*S*k^5*exp(6*k) - 128*AK*S*k^5*exp(2*k) - ...
            8*AK*S*k^4*exp(8*k) + 32*AK*S*k^4*exp(6*k) + 80*AK*S*k^4*exp(4*k) ...
            + 32*AK*S*k^4*exp(2*k) - 8*AK*S*k^4 - 256*AK*cotbeta*k^6*exp(4*k) ...
            - 64*AK*cotbeta*k^4*exp(6*k) - 640*AK*cotbeta*k^4*exp(4*k) - ...
            64*AK*cotbeta*k^4*exp(2*k) + 256*AK*cotbeta*k^3*exp(6*k) - ...
            256*AK*cotbeta*k^3*exp(2*k) - 32*AK*cotbeta*k^2*exp(8*k) + ...
            64*AK*cotbeta*k^2*exp(4*k) - 32*AK*cotbeta*k^2 + ...
            256*i*AK*k^7*exp(4*k) - 64*i*AK*k^6*exp(6*k) + ...
            64*i*AK*k^6*exp(2*k) + 192*i*AK*k^5*exp(6*k) + ...
            640*i*AK*k^5*exp(4*k) + 192*i*AK*k^5*exp(2*k) - ...
            16*i*AK*k^4*exp(8*k) - 160*i*AK*k^4*exp(6*k) + ...
            160*i*AK*k^4*exp(2*k) + 16*i*AK*k^4 + 32*i*AK*k^3*exp(8*k) + ...
            64*i*AK*k^3*exp(6*k) + 64*i*AK*k^3*exp(4*k) + 64*i*AK*k^3*exp(2*k) ...
            + 32*i*AK*k^3 + 64*AT^2*k^10*exp(4*k) + 32*AT^2*k^8*exp(6*k) + ...
            64*AT^2*k^8*exp(4*k) + 32*AT^2*k^8*exp(2*k) + 4*AT^2*k^6*exp(8*k) ...
            + 16*AT^2*k^6*exp(6*k) + 24*AT^2*k^6*exp(4*k) + ...
            16*AT^2*k^6*exp(2*k) + 4*AT^2*k^6 + 32*AT*S*k^8*exp(6*k) - ...
            192*AT*S*k^8*exp(4*k) + 32*AT*S*k^8*exp(2*k) + ...
            128*AT*S*k^7*exp(6*k) - 128*AT*S*k^7*exp(2*k) - ...
            8*AT*S*k^6*exp(8*k) + 32*AT*S*k^6*exp(6*k) + 80*AT*S*k^6*exp(4*k) ...
            + 32*AT*S*k^6*exp(2*k) - 8*AT*S*k^6 - 256*AT*cotbeta*k^8*exp(4*k) ...
            - 64*AT*cotbeta*k^6*exp(6*k) - 640*AT*cotbeta*k^6*exp(4*k) - ...
            64*AT*cotbeta*k^6*exp(2*k) + 256*AT*cotbeta*k^5*exp(6*k) - ...
            256*AT*cotbeta*k^5*exp(2*k) - 32*AT*cotbeta*k^4*exp(8*k) + ...
            64*AT*cotbeta*k^4*exp(4*k) - 32*AT*cotbeta*k^4 + ...
            256*i*AT*k^9*exp(4*k) - 64*i*AT*k^8*exp(6*k) + ...
            64*i*AT*k^8*exp(2*k) + 192*i*AT*k^7*exp(6*k) + ...
            640*i*AT*k^7*exp(4*k) + 192*i*AT*k^7*exp(2*k) - ...
            16*i*AT*k^6*exp(8*k) - 160*i*AT*k^6*exp(6*k) + ...
            160*i*AT*k^6*exp(2*k) + 16*i*AT*k^6 + 32*i*AT*k^5*exp(8*k) + ...
            64*i*AT*k^5*exp(6*k) + 64*i*AT*k^5*exp(4*k) + 64*i*AT*k^5*exp(2*k) ...
            + 32*i*AT*k^5 + 4*S^2*k^6*exp(8*k) + 16*S^2*k^6*exp(6*k) + ...
            24*S^2*k^6*exp(4*k) + 16*S^2*k^6*exp(2*k) + 4*S^2*k^6 - ...
            64*S*cotbeta*k^6*exp(6*k) + 384*S*cotbeta*k^6*exp(4*k) - ...
            64*S*cotbeta*k^6*exp(2*k) - 256*S*cotbeta*k^5*exp(6*k) + ...
            256*S*cotbeta*k^5*exp(2*k) + 32*S*cotbeta*k^4*exp(8*k) - ...
            64*S*cotbeta*k^4*exp(4*k) + 32*S*cotbeta*k^4 - 64*i*S*k^7*exp(6*k) ...
            - 128*i*S*k^7*exp(4*k) - 64*i*S*k^7*exp(2*k) + 16*i*S*k^6*exp(8*k) ...
            + 288*i*S*k^6*exp(6*k) - 288*i*S*k^6*exp(2*k) - 16*i*S*k^6 - ...
            32*i*S*k^5*exp(8*k) + 64*i*S*k^5*exp(6*k) + 192*i*S*k^5*exp(4*k) + ...
            64*i*S*k^5*exp(2*k) - 32*i*S*k^5 + 256*cotbeta^2*k^6*exp(4*k) + ...
            1024*cotbeta^2*k^4*exp(4*k) - 512*cotbeta^2*k^3*exp(6*k) + ...
            512*cotbeta^2*k^3*exp(2*k) + 64*cotbeta^2*k^2*exp(8*k) - ...
            128*cotbeta^2*k^2*exp(4*k) + 64*cotbeta^2*k^2 - ...
            512*i*cotbeta*k^7*exp(4*k) + 128*i*cotbeta*k^6*exp(6*k) - ...
            128*i*cotbeta*k^6*exp(2*k) - 512*i*cotbeta*k^5*exp(6*k) - ...
            1536*i*cotbeta*k^5*exp(4*k) - 512*i*cotbeta*k^5*exp(2*k) + ...
            64*i*cotbeta*k^4*exp(8*k) + 896*i*cotbeta*k^4*exp(6*k) - ...
            896*i*cotbeta*k^4*exp(2*k) - 64*i*cotbeta*k^4 - ...
            128*i*cotbeta*k^3*exp(8*k) + 256*i*cotbeta*k^3*exp(4*k) - ...
            128*i*cotbeta*k^3 - 256*k^8*exp(4*k) + 128*k^7*exp(6*k) - ...
            128*k^7*exp(2*k) - 16*k^6*exp(8*k) - 256*k^6*exp(6*k) - ...
            992*k^6*exp(4*k) - 256*k^6*exp(2*k) - 16*k^6 + 64*k^5*exp(8*k) + ...
            256*k^5*exp(6*k) - 256*k^5*exp(2*k) - 64*k^5 - 64*k^4*exp(8*k) - ...
            128*k^4*exp(4*k) - 64*k^4))./(16*AD*k^4*exp(2*k) + ...
            4*AD*k^2*exp(4*k) + 8*AD*k^2*exp(2*k) + 4*AD*k^2 - 32*k^4*exp(2*k) ...
            + 8*k^3*exp(4*k) - 8*k^3), -(8*i*AB*k^7*exp(2*k) + ...
            2*i*AB*k^5*exp(4*k) + 4*i*AB*k^5*exp(2*k) + 2*i*AB*k^5 - ...
            4*i*AD*S*k^3*exp(2*k) + i*AD*S*k^2*exp(4*k) - i*AD*S*k^2 - ...
            8*i*AD*cotbeta*k*exp(2*k) + 2*i*AD*cotbeta*exp(4*k) - ...
            2*i*AD*cotbeta - 8*AD*k^4*exp(2*k) - 2*AD*k^2*exp(4*k) - ...
            12*AD*k^2*exp(2*k) - 2*AD*k^2 + 8*i*AK*k^3*exp(2*k) + ...
            2*i*AK*k*exp(4*k) + 4*i*AK*k*exp(2*k) + 2*i*AK*k + ...
            8*i*AT*k^5*exp(2*k) + 2*i*AT*k^3*exp(4*k) + 4*i*AT*k^3*exp(2*k) + ...
            2*i*AT*k^3 + 2*i*S*k^3*exp(4*k) + 4*i*S*k^3*exp(2*k) + 2*i*S*k^3 - ...
            16*i*cotbeta*k^3*exp(2*k) + 16*k^4*exp(2*k) - 4*k^3*exp(4*k) + ...
            4*k^3 - 8*k^2*exp(4*k) - 8*k^2 + i*sqrt(64*AB^2*k^14*exp(4*k) + ...
            32*AB^2*k^12*exp(6*k) + 64*AB^2*k^12*exp(4*k) + ...
            32*AB^2*k^12*exp(2*k) + 4*AB^2*k^10*exp(8*k) + ...
            16*AB^2*k^10*exp(6*k) + 24*AB^2*k^10*exp(4*k) + ...
            16*AB^2*k^10*exp(2*k) + 4*AB^2*k^10 + 64*AB*AD*S*k^10*exp(4*k) - ...
            16*AB*AD*S*k^9*exp(6*k) + 16*AB*AD*S*k^9*exp(2*k) + ...
            16*AB*AD*S*k^8*exp(6*k) + 32*AB*AD*S*k^8*exp(4*k) + ...
            16*AB*AD*S*k^8*exp(2*k) - 4*AB*AD*S*k^7*exp(8*k) - ...
            8*AB*AD*S*k^7*exp(6*k) + 8*AB*AD*S*k^7*exp(2*k) + 4*AB*AD*S*k^7 + ...
            128*AB*AD*cotbeta*k^8*exp(4*k) - 32*AB*AD*cotbeta*k^7*exp(6*k) + ...
            32*AB*AD*cotbeta*k^7*exp(2*k) + 32*AB*AD*cotbeta*k^6*exp(6*k) + ...
            64*AB*AD*cotbeta*k^6*exp(4*k) + 32*AB*AD*cotbeta*k^6*exp(2*k) - ...
            8*AB*AD*cotbeta*k^5*exp(8*k) - 16*AB*AD*cotbeta*k^5*exp(6*k) + ...
            16*AB*AD*cotbeta*k^5*exp(2*k) + 8*AB*AD*cotbeta*k^5 - ...
            128*i*AB*AD*k^11*exp(4*k) - 64*i*AB*AD*k^9*exp(6*k) - ...
            256*i*AB*AD*k^9*exp(4*k) - 64*i*AB*AD*k^9*exp(2*k) - ...
            8*i*AB*AD*k^7*exp(8*k) - 64*i*AB*AD*k^7*exp(6*k) - ...
            112*i*AB*AD*k^7*exp(4*k) - 64*i*AB*AD*k^7*exp(2*k) - 8*i*AB*AD*k^7 ...
            + 128*AB*AK*k^10*exp(4*k) + 64*AB*AK*k^8*exp(6*k) + ...
            128*AB*AK*k^8*exp(4*k) + 64*AB*AK*k^8*exp(2*k) + ...
            8*AB*AK*k^6*exp(8*k) + 32*AB*AK*k^6*exp(6*k) + ...
            48*AB*AK*k^6*exp(4*k) + 32*AB*AK*k^6*exp(2*k) + 8*AB*AK*k^6 + ...
            128*AB*AT*k^12*exp(4*k) + 64*AB*AT*k^10*exp(6*k) + ...
            128*AB*AT*k^10*exp(4*k) + 64*AB*AT*k^10*exp(2*k) + ...
            8*AB*AT*k^8*exp(8*k) + 32*AB*AT*k^8*exp(6*k) + ...
            48*AB*AT*k^8*exp(4*k) + 32*AB*AT*k^8*exp(2*k) + 8*AB*AT*k^8 + ...
            32*AB*S*k^10*exp(6*k) - 192*AB*S*k^10*exp(4*k) + ...
            32*AB*S*k^10*exp(2*k) + 128*AB*S*k^9*exp(6*k) - ...
            128*AB*S*k^9*exp(2*k) - 8*AB*S*k^8*exp(8*k) + 32*AB*S*k^8*exp(6*k) ...
            + 80*AB*S*k^8*exp(4*k) + 32*AB*S*k^8*exp(2*k) - 8*AB*S*k^8 - ...
            256*AB*cotbeta*k^10*exp(4*k) - 64*AB*cotbeta*k^8*exp(6*k) - ...
            640*AB*cotbeta*k^8*exp(4*k) - 64*AB*cotbeta*k^8*exp(2*k) + ...
            256*AB*cotbeta*k^7*exp(6*k) - 256*AB*cotbeta*k^7*exp(2*k) - ...
            32*AB*cotbeta*k^6*exp(8*k) + 64*AB*cotbeta*k^6*exp(4*k) - ...
            32*AB*cotbeta*k^6 + 256*i*AB*k^11*exp(4*k) - 64*i*AB*k^10*exp(6*k) ...
            + 64*i*AB*k^10*exp(2*k) + 192*i*AB*k^9*exp(6*k) + ...
            640*i*AB*k^9*exp(4*k) + 192*i*AB*k^9*exp(2*k) - ...
            16*i*AB*k^8*exp(8*k) - 160*i*AB*k^8*exp(6*k) + ...
            160*i*AB*k^8*exp(2*k) + 16*i*AB*k^8 + 32*i*AB*k^7*exp(8*k) + ...
            64*i*AB*k^7*exp(6*k) + 64*i*AB*k^7*exp(4*k) + 64*i*AB*k^7*exp(2*k) ...
            + 32*i*AB*k^7 + 16*AD^2*S^2*k^6*exp(4*k) - 8*AD^2*S^2*k^5*exp(6*k) ...
            + 8*AD^2*S^2*k^5*exp(2*k) + AD^2*S^2*k^4*exp(8*k) - ...
            2*AD^2*S^2*k^4*exp(4*k) + AD^2*S^2*k^4 + ...
            64*AD^2*S*cotbeta*k^4*exp(4*k) - 32*AD^2*S*cotbeta*k^3*exp(6*k) + ...
            32*AD^2*S*cotbeta*k^3*exp(2*k) + 4*AD^2*S*cotbeta*k^2*exp(8*k) - ...
            8*AD^2*S*cotbeta*k^2*exp(4*k) + 4*AD^2*S*cotbeta*k^2 - ...
            64*i*AD^2*S*k^7*exp(4*k) + 16*i*AD^2*S*k^6*exp(6*k) - ...
            16*i*AD^2*S*k^6*exp(2*k) - 16*i*AD^2*S*k^5*exp(6*k) - ...
            96*i*AD^2*S*k^5*exp(4*k) - 16*i*AD^2*S*k^5*exp(2*k) + ...
            4*i*AD^2*S*k^4*exp(8*k) + 24*i*AD^2*S*k^4*exp(6*k) - ...
            24*i*AD^2*S*k^4*exp(2*k) - 4*i*AD^2*S*k^4 + ...
            64*AD^2*cotbeta^2*k^2*exp(4*k) - 32*AD^2*cotbeta^2*k*exp(6*k) + ...
            32*AD^2*cotbeta^2*k*exp(2*k) + 4*AD^2*cotbeta^2*exp(8*k) - ...
            8*AD^2*cotbeta^2*exp(4*k) + 4*AD^2*cotbeta^2 - ...
            128*i*AD^2*cotbeta*k^5*exp(4*k) + 32*i*AD^2*cotbeta*k^4*exp(6*k) - ...
            32*i*AD^2*cotbeta*k^4*exp(2*k) - 32*i*AD^2*cotbeta*k^3*exp(6*k) - ...
            192*i*AD^2*cotbeta*k^3*exp(4*k) - 32*i*AD^2*cotbeta*k^3*exp(2*k) + ...
            8*i*AD^2*cotbeta*k^2*exp(8*k) + 48*i*AD^2*cotbeta*k^2*exp(6*k) - ...
            48*i*AD^2*cotbeta*k^2*exp(2*k) - 8*i*AD^2*cotbeta*k^2 - ...
            64*AD^2*k^8*exp(4*k) - 32*AD^2*k^6*exp(6*k) - ...
            192*AD^2*k^6*exp(4*k) - 32*AD^2*k^6*exp(2*k) - 4*AD^2*k^4*exp(8*k) ...
            - 48*AD^2*k^4*exp(6*k) - 152*AD^2*k^4*exp(4*k) - ...
            48*AD^2*k^4*exp(2*k) - 4*AD^2*k^4 + 64*AD*AK*S*k^6*exp(4*k) - ...
            16*AD*AK*S*k^5*exp(6*k) + 16*AD*AK*S*k^5*exp(2*k) + ...
            16*AD*AK*S*k^4*exp(6*k) + 32*AD*AK*S*k^4*exp(4*k) + ...
            16*AD*AK*S*k^4*exp(2*k) - 4*AD*AK*S*k^3*exp(8*k) - ...
            8*AD*AK*S*k^3*exp(6*k) + 8*AD*AK*S*k^3*exp(2*k) + 4*AD*AK*S*k^3 + ...
            128*AD*AK*cotbeta*k^4*exp(4*k) - 32*AD*AK*cotbeta*k^3*exp(6*k) + ...
            32*AD*AK*cotbeta*k^3*exp(2*k) + 32*AD*AK*cotbeta*k^2*exp(6*k) + ...
            64*AD*AK*cotbeta*k^2*exp(4*k) + 32*AD*AK*cotbeta*k^2*exp(2*k) - ...
            8*AD*AK*cotbeta*k*exp(8*k) - 16*AD*AK*cotbeta*k*exp(6*k) + ...
            16*AD*AK*cotbeta*k*exp(2*k) + 8*AD*AK*cotbeta*k - ...
            128*i*AD*AK*k^7*exp(4*k) - 64*i*AD*AK*k^5*exp(6*k) - ...
            256*i*AD*AK*k^5*exp(4*k) - 64*i*AD*AK*k^5*exp(2*k) - ...
            8*i*AD*AK*k^3*exp(8*k) - 64*i*AD*AK*k^3*exp(6*k) - ...
            112*i*AD*AK*k^3*exp(4*k) - 64*i*AD*AK*k^3*exp(2*k) - 8*i*AD*AK*k^3 ...
            + 64*AD*AT*S*k^8*exp(4*k) - 16*AD*AT*S*k^7*exp(6*k) + ...
            16*AD*AT*S*k^7*exp(2*k) + 16*AD*AT*S*k^6*exp(6*k) + ...
            32*AD*AT*S*k^6*exp(4*k) + 16*AD*AT*S*k^6*exp(2*k) - ...
            4*AD*AT*S*k^5*exp(8*k) - 8*AD*AT*S*k^5*exp(6*k) + ...
            8*AD*AT*S*k^5*exp(2*k) + 4*AD*AT*S*k^5 + ...
            128*AD*AT*cotbeta*k^6*exp(4*k) - 32*AD*AT*cotbeta*k^5*exp(6*k) + ...
            32*AD*AT*cotbeta*k^5*exp(2*k) + 32*AD*AT*cotbeta*k^4*exp(6*k) + ...
            64*AD*AT*cotbeta*k^4*exp(4*k) + 32*AD*AT*cotbeta*k^4*exp(2*k) - ...
            8*AD*AT*cotbeta*k^3*exp(8*k) - 16*AD*AT*cotbeta*k^3*exp(6*k) + ...
            16*AD*AT*cotbeta*k^3*exp(2*k) + 8*AD*AT*cotbeta*k^3 - ...
            128*i*AD*AT*k^9*exp(4*k) - 64*i*AD*AT*k^7*exp(6*k) - ...
            256*i*AD*AT*k^7*exp(4*k) - 64*i*AD*AT*k^7*exp(2*k) - ...
            8*i*AD*AT*k^5*exp(8*k) - 64*i*AD*AT*k^5*exp(6*k) - ...
            112*i*AD*AT*k^5*exp(4*k) - 64*i*AD*AT*k^5*exp(2*k) - 8*i*AD*AT*k^5 ...
            - 16*AD*S^2*k^6*exp(6*k) - 32*AD*S^2*k^6*exp(4*k) - ...
            16*AD*S^2*k^6*exp(2*k) + 4*AD*S^2*k^5*exp(8*k) + ...
            8*AD*S^2*k^5*exp(6*k) - 8*AD*S^2*k^5*exp(2*k) - 4*AD*S^2*k^5 - ...
            128*AD*S*cotbeta*k^6*exp(4*k) + 32*AD*S*cotbeta*k^5*exp(6*k) - ...
            32*AD*S*cotbeta*k^5*exp(2*k) - 96*AD*S*cotbeta*k^4*exp(6*k) - ...
            192*AD*S*cotbeta*k^4*exp(4*k) - 96*AD*S*cotbeta*k^4*exp(2*k) + ...
            24*AD*S*cotbeta*k^3*exp(8*k) + 48*AD*S*cotbeta*k^3*exp(6*k) - ...
            48*AD*S*cotbeta*k^3*exp(2*k) - 24*AD*S*cotbeta*k^3 + ...
            32*i*AD*S*k^7*exp(6*k) + 192*i*AD*S*k^7*exp(4*k) + ...
            32*i*AD*S*k^7*exp(2*k) - 192*i*AD*S*k^6*exp(6*k) + ...
            192*i*AD*S*k^6*exp(2*k) + 16*i*AD*S*k^5*exp(8*k) + ...
            96*i*AD*S*k^5*exp(4*k) + 16*i*AD*S*k^5 - 16*i*AD*S*k^4*exp(8*k) - ...
            64*i*AD*S*k^4*exp(6*k) + 64*i*AD*S*k^4*exp(2*k) + 16*i*AD*S*k^4 - ...
            256*AD*cotbeta^2*k^4*exp(4*k) + 64*AD*cotbeta^2*k^3*exp(6*k) - ...
            64*AD*cotbeta^2*k^3*exp(2*k) - 128*AD*cotbeta^2*k^2*exp(6*k) - ...
            256*AD*cotbeta^2*k^2*exp(4*k) - 128*AD*cotbeta^2*k^2*exp(2*k) + ...
            32*AD*cotbeta^2*k*exp(8*k) + 64*AD*cotbeta^2*k*exp(6*k) - ...
            64*AD*cotbeta^2*k*exp(2*k) - 32*AD*cotbeta^2*k + ...
            256*i*AD*cotbeta*k^7*exp(4*k) + 192*i*AD*cotbeta*k^5*exp(6*k) + ...
            896*i*AD*cotbeta*k^5*exp(4*k) + 192*i*AD*cotbeta*k^5*exp(2*k) - ...
            384*i*AD*cotbeta*k^4*exp(6*k) + 384*i*AD*cotbeta*k^4*exp(2*k) + ...
            48*i*AD*cotbeta*k^3*exp(8*k) + 128*i*AD*cotbeta*k^3*exp(6*k) + ...
            416*i*AD*cotbeta*k^3*exp(4*k) + 128*i*AD*cotbeta*k^3*exp(2*k) + ...
            48*i*AD*cotbeta*k^3 - 32*i*AD*cotbeta*k^2*exp(8*k) - ...
            128*i*AD*cotbeta*k^2*exp(6*k) + 128*i*AD*cotbeta*k^2*exp(2*k) + ...
            32*i*AD*cotbeta*k^2 + 256*AD*k^8*exp(4*k) - 64*AD*k^7*exp(6*k) + ...
            64*AD*k^7*exp(2*k) + 192*AD*k^6*exp(6*k) + 896*AD*k^6*exp(4*k) + ...
            192*AD*k^6*exp(2*k) - 16*AD*k^5*exp(8*k) - 96*AD*k^5*exp(6*k) + ...
            96*AD*k^5*exp(2*k) + 16*AD*k^5 + 32*AD*k^4*exp(8*k) + ...
            64*AD*k^4*exp(6*k) + 320*AD*k^4*exp(4*k) + 64*AD*k^4*exp(2*k) + ...
            32*AD*k^4 + 64*AK^2*k^6*exp(4*k) + 32*AK^2*k^4*exp(6*k) + ...
            64*AK^2*k^4*exp(4*k) + 32*AK^2*k^4*exp(2*k) + 4*AK^2*k^2*exp(8*k) ...
            + 16*AK^2*k^2*exp(6*k) + 24*AK^2*k^2*exp(4*k) + ...
            16*AK^2*k^2*exp(2*k) + 4*AK^2*k^2 + 128*AK*AT*k^8*exp(4*k) + ...
            64*AK*AT*k^6*exp(6*k) + 128*AK*AT*k^6*exp(4*k) + ...
            64*AK*AT*k^6*exp(2*k) + 8*AK*AT*k^4*exp(8*k) + ...
            32*AK*AT*k^4*exp(6*k) + 48*AK*AT*k^4*exp(4*k) + ...
            32*AK*AT*k^4*exp(2*k) + 8*AK*AT*k^4 + 32*AK*S*k^6*exp(6*k) - ...
            192*AK*S*k^6*exp(4*k) + 32*AK*S*k^6*exp(2*k) + ...
            128*AK*S*k^5*exp(6*k) - 128*AK*S*k^5*exp(2*k) - ...
            8*AK*S*k^4*exp(8*k) + 32*AK*S*k^4*exp(6*k) + 80*AK*S*k^4*exp(4*k) ...
            + 32*AK*S*k^4*exp(2*k) - 8*AK*S*k^4 - 256*AK*cotbeta*k^6*exp(4*k) ...
            - 64*AK*cotbeta*k^4*exp(6*k) - 640*AK*cotbeta*k^4*exp(4*k) - ...
            64*AK*cotbeta*k^4*exp(2*k) + 256*AK*cotbeta*k^3*exp(6*k) - ...
            256*AK*cotbeta*k^3*exp(2*k) - 32*AK*cotbeta*k^2*exp(8*k) + ...
            64*AK*cotbeta*k^2*exp(4*k) - 32*AK*cotbeta*k^2 + ...
            256*i*AK*k^7*exp(4*k) - 64*i*AK*k^6*exp(6*k) + ...
            64*i*AK*k^6*exp(2*k) + 192*i*AK*k^5*exp(6*k) + ...
            640*i*AK*k^5*exp(4*k) + 192*i*AK*k^5*exp(2*k) - ...
            16*i*AK*k^4*exp(8*k) - 160*i*AK*k^4*exp(6*k) + ...
            160*i*AK*k^4*exp(2*k) + 16*i*AK*k^4 + 32*i*AK*k^3*exp(8*k) + ...
            64*i*AK*k^3*exp(6*k) + 64*i*AK*k^3*exp(4*k) + 64*i*AK*k^3*exp(2*k) ...
            + 32*i*AK*k^3 + 64*AT^2*k^10*exp(4*k) + 32*AT^2*k^8*exp(6*k) + ...
            64*AT^2*k^8*exp(4*k) + 32*AT^2*k^8*exp(2*k) + 4*AT^2*k^6*exp(8*k) ...
            + 16*AT^2*k^6*exp(6*k) + 24*AT^2*k^6*exp(4*k) + ...
            16*AT^2*k^6*exp(2*k) + 4*AT^2*k^6 + 32*AT*S*k^8*exp(6*k) - ...
            192*AT*S*k^8*exp(4*k) + 32*AT*S*k^8*exp(2*k) + ...
            128*AT*S*k^7*exp(6*k) - 128*AT*S*k^7*exp(2*k) - ...
            8*AT*S*k^6*exp(8*k) + 32*AT*S*k^6*exp(6*k) + 80*AT*S*k^6*exp(4*k) ...
            + 32*AT*S*k^6*exp(2*k) - 8*AT*S*k^6 - 256*AT*cotbeta*k^8*exp(4*k) ...
            - 64*AT*cotbeta*k^6*exp(6*k) - 640*AT*cotbeta*k^6*exp(4*k) - ...
            64*AT*cotbeta*k^6*exp(2*k) + 256*AT*cotbeta*k^5*exp(6*k) - ...
            256*AT*cotbeta*k^5*exp(2*k) - 32*AT*cotbeta*k^4*exp(8*k) + ...
            64*AT*cotbeta*k^4*exp(4*k) - 32*AT*cotbeta*k^4 + ...
            256*i*AT*k^9*exp(4*k) - 64*i*AT*k^8*exp(6*k) + ...
            64*i*AT*k^8*exp(2*k) + 192*i*AT*k^7*exp(6*k) + ...
            640*i*AT*k^7*exp(4*k) + 192*i*AT*k^7*exp(2*k) - ...
            16*i*AT*k^6*exp(8*k) - 160*i*AT*k^6*exp(6*k) + ...
            160*i*AT*k^6*exp(2*k) + 16*i*AT*k^6 + 32*i*AT*k^5*exp(8*k) + ...
            64*i*AT*k^5*exp(6*k) + 64*i*AT*k^5*exp(4*k) + 64*i*AT*k^5*exp(2*k) ...
            + 32*i*AT*k^5 + 4*S^2*k^6*exp(8*k) + 16*S^2*k^6*exp(6*k) + ...
            24*S^2*k^6*exp(4*k) + 16*S^2*k^6*exp(2*k) + 4*S^2*k^6 - ...
            64*S*cotbeta*k^6*exp(6*k) + 384*S*cotbeta*k^6*exp(4*k) - ...
            64*S*cotbeta*k^6*exp(2*k) - 256*S*cotbeta*k^5*exp(6*k) + ...
            256*S*cotbeta*k^5*exp(2*k) + 32*S*cotbeta*k^4*exp(8*k) - ...
            64*S*cotbeta*k^4*exp(4*k) + 32*S*cotbeta*k^4 - 64*i*S*k^7*exp(6*k) ...
            - 128*i*S*k^7*exp(4*k) - 64*i*S*k^7*exp(2*k) + 16*i*S*k^6*exp(8*k) ...
            + 288*i*S*k^6*exp(6*k) - 288*i*S*k^6*exp(2*k) - 16*i*S*k^6 - ...
            32*i*S*k^5*exp(8*k) + 64*i*S*k^5*exp(6*k) + 192*i*S*k^5*exp(4*k) + ...
            64*i*S*k^5*exp(2*k) - 32*i*S*k^5 + 256*cotbeta^2*k^6*exp(4*k) + ...
            1024*cotbeta^2*k^4*exp(4*k) - 512*cotbeta^2*k^3*exp(6*k) + ...
            512*cotbeta^2*k^3*exp(2*k) + 64*cotbeta^2*k^2*exp(8*k) - ...
            128*cotbeta^2*k^2*exp(4*k) + 64*cotbeta^2*k^2 - ...
            512*i*cotbeta*k^7*exp(4*k) + 128*i*cotbeta*k^6*exp(6*k) - ...
            128*i*cotbeta*k^6*exp(2*k) - 512*i*cotbeta*k^5*exp(6*k) - ...
            1536*i*cotbeta*k^5*exp(4*k) - 512*i*cotbeta*k^5*exp(2*k) + ...
            64*i*cotbeta*k^4*exp(8*k) + 896*i*cotbeta*k^4*exp(6*k) - ...
            896*i*cotbeta*k^4*exp(2*k) - 64*i*cotbeta*k^4 - ...
            128*i*cotbeta*k^3*exp(8*k) + 256*i*cotbeta*k^3*exp(4*k) - ...
            128*i*cotbeta*k^3 - 256*k^8*exp(4*k) + 128*k^7*exp(6*k) - ...
            128*k^7*exp(2*k) - 16*k^6*exp(8*k) - 256*k^6*exp(6*k) - ...
            992*k^6*exp(4*k) - 256*k^6*exp(2*k) - 16*k^6 + 64*k^5*exp(8*k) + ...
            256*k^5*exp(6*k) - 256*k^5*exp(2*k) - 64*k^5 - 64*k^4*exp(8*k) - ...
            128*k^4*exp(4*k) - 64*k^4))./(16*AD*k^4*exp(2*k) + ...
            4*AD*k^2*exp(4*k) + 8*AD*k^2*exp(2*k) + 4*AD*k^2 - 32*k^4*exp(2*k) ...
            + 8*k^3*exp(4*k) - 8*k^3)];
    else
        out = [-(3.*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + ...
            2.*AI.*k.^3.*exp(4.*k) + 4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).^2)./(3.*(sqrt(-4.*(3.*(8.*AB.*k.^7.*exp(2.*k) + ...
            2.*AB.*k.^5.*exp(4.*k) + 4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - ...
            4.*AD.*S.*k.^3.*exp(2.*k) + AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + ...
            8.*i.*AD.*k.^4.*exp(2.*k) + 2.*i.*AD.*k.^2.*exp(4.*k) + ...
            12.*i.*AD.*k.^2.*exp(2.*k) + 2.*i.*AD.*k.^2 - ...
            8.*AD.*k.*cotbeta.*exp(2.*k) + 2.*AD.*cotbeta.*exp(4.*k) - ...
            2.*AD.*cotbeta + 8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + ...
            4.*AK.*k.*exp(2.*k) + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + ...
            2.*AT.*k.^3.*exp(4.*k) + 4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + ...
            2.*S.*k.^3.*exp(4.*k) + 4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - ...
            16.*i.*k.^4.*exp(2.*k) - 16.*k.^3.*cotbeta.*exp(2.*k) + ...
            4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 + 8.*i.*k.^2.*exp(4.*k) + ...
            8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + (8.*i.*AD.*k.^3.*exp(2.*k) ...
            + 2.*i.*AD.*k.*exp(4.*k) + 4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2).^3 + ...
            (27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./((8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            2.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^2)./2 + ...
            27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(2.*(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4)) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(2.*(8.*AI.*k.^4.*exp(2.*k) ...
            + 2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^(1./3)) - ...
            (sqrt(-4.*(3.*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + ...
            2.*AI.*k.^3.*exp(4.*k) + 4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2).^3 + ...
            (27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./((8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            2.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^2)./2 + ...
            27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(2.*(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4)) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(2.*(8.*AI.*k.^4.*exp(2.*k) ...
            + 2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^(1./3)./3 - ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2)./(3.*(8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2)), ...
            -(3.*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + ...
            2.*AI.*k.^3.*exp(4.*k) + 4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2)./(3.*(-1./2 - ...
            sqrt(3).*i./2).*(sqrt(-4.*(3.*(8.*AB.*k.^7.*exp(2.*k) + ...
            2.*AB.*k.^5.*exp(4.*k) + 4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - ...
            4.*AD.*S.*k.^3.*exp(2.*k) + AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + ...
            8.*i.*AD.*k.^4.*exp(2.*k) + 2.*i.*AD.*k.^2.*exp(4.*k) + ...
            12.*i.*AD.*k.^2.*exp(2.*k) + 2.*i.*AD.*k.^2 - ...
            8.*AD.*k.*cotbeta.*exp(2.*k) + 2.*AD.*cotbeta.*exp(4.*k) - ...
            2.*AD.*cotbeta + 8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + ...
            4.*AK.*k.*exp(2.*k) + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + ...
            2.*AT.*k.^3.*exp(4.*k) + 4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + ...
            2.*S.*k.^3.*exp(4.*k) + 4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - ...
            16.*i.*k.^4.*exp(2.*k) - 16.*k.^3.*cotbeta.*exp(2.*k) + ...
            4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 + 8.*i.*k.^2.*exp(4.*k) + ...
            8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + (8.*i.*AD.*k.^3.*exp(2.*k) ...
            + 2.*i.*AD.*k.*exp(4.*k) + 4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2).^3 + ...
            (27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./((8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            2.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^2)./2 + ...
            27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(2.*(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4)) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(2.*(8.*AI.*k.^4.*exp(2.*k) ...
            + 2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^(1./3)) - (-1./2 - ...
            sqrt(3).*i./2).*(sqrt(-4.*(3.*(8.*AB.*k.^7.*exp(2.*k) + ...
            2.*AB.*k.^5.*exp(4.*k) + 4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - ...
            4.*AD.*S.*k.^3.*exp(2.*k) + AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + ...
            8.*i.*AD.*k.^4.*exp(2.*k) + 2.*i.*AD.*k.^2.*exp(4.*k) + ...
            12.*i.*AD.*k.^2.*exp(2.*k) + 2.*i.*AD.*k.^2 - ...
            8.*AD.*k.*cotbeta.*exp(2.*k) + 2.*AD.*cotbeta.*exp(4.*k) - ...
            2.*AD.*cotbeta + 8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + ...
            4.*AK.*k.*exp(2.*k) + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + ...
            2.*AT.*k.^3.*exp(4.*k) + 4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + ...
            2.*S.*k.^3.*exp(4.*k) + 4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - ...
            16.*i.*k.^4.*exp(2.*k) - 16.*k.^3.*cotbeta.*exp(2.*k) + ...
            4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 + 8.*i.*k.^2.*exp(4.*k) + ...
            8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + (8.*i.*AD.*k.^3.*exp(2.*k) ...
            + 2.*i.*AD.*k.*exp(4.*k) + 4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2).^3 + ...
            (27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./((8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            2.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^2)./2 + ...
            27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(2.*(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4)) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(2.*(8.*AI.*k.^4.*exp(2.*k) ...
            + 2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^(1./3)./3 - ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2)./(3.*(8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2)), ...
            -(3.*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + ...
            2.*AI.*k.^3.*exp(4.*k) + 4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2)./(3.*(-1./2 + ...
            sqrt(3).*i./2).*(sqrt(-4.*(3.*(8.*AB.*k.^7.*exp(2.*k) + ...
            2.*AB.*k.^5.*exp(4.*k) + 4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - ...
            4.*AD.*S.*k.^3.*exp(2.*k) + AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + ...
            8.*i.*AD.*k.^4.*exp(2.*k) + 2.*i.*AD.*k.^2.*exp(4.*k) + ...
            12.*i.*AD.*k.^2.*exp(2.*k) + 2.*i.*AD.*k.^2 - ...
            8.*AD.*k.*cotbeta.*exp(2.*k) + 2.*AD.*cotbeta.*exp(4.*k) - ...
            2.*AD.*cotbeta + 8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + ...
            4.*AK.*k.*exp(2.*k) + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + ...
            2.*AT.*k.^3.*exp(4.*k) + 4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + ...
            2.*S.*k.^3.*exp(4.*k) + 4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - ...
            16.*i.*k.^4.*exp(2.*k) - 16.*k.^3.*cotbeta.*exp(2.*k) + ...
            4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 + 8.*i.*k.^2.*exp(4.*k) + ...
            8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + (8.*i.*AD.*k.^3.*exp(2.*k) ...
            + 2.*i.*AD.*k.*exp(4.*k) + 4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2).^3 + ...
            (27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./((8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            2.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^2)./2 + ...
            27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(2.*(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4)) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(2.*(8.*AI.*k.^4.*exp(2.*k) ...
            + 2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^(1./3)) - (-1./2 + ...
            sqrt(3).*i./2).*(sqrt(-4.*(3.*(8.*AB.*k.^7.*exp(2.*k) + ...
            2.*AB.*k.^5.*exp(4.*k) + 4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - ...
            4.*AD.*S.*k.^3.*exp(2.*k) + AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + ...
            8.*i.*AD.*k.^4.*exp(2.*k) + 2.*i.*AD.*k.^2.*exp(4.*k) + ...
            12.*i.*AD.*k.^2.*exp(2.*k) + 2.*i.*AD.*k.^2 - ...
            8.*AD.*k.*cotbeta.*exp(2.*k) + 2.*AD.*cotbeta.*exp(4.*k) - ...
            2.*AD.*cotbeta + 8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + ...
            4.*AK.*k.*exp(2.*k) + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + ...
            2.*AT.*k.^3.*exp(4.*k) + 4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + ...
            2.*S.*k.^3.*exp(4.*k) + 4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - ...
            16.*i.*k.^4.*exp(2.*k) - 16.*k.^3.*cotbeta.*exp(2.*k) + ...
            4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 + 8.*i.*k.^2.*exp(4.*k) + ...
            8.*i.*k.^2)./(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3) + (8.*i.*AD.*k.^3.*exp(2.*k) ...
            + 2.*i.*AD.*k.*exp(4.*k) + 4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^2./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^2).^3 + ...
            (27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./((8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            2.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^2)./2 + ...
            27.*(4.*i.*AB.*S.*k.^7.*exp(2.*k) - i.*AB.*S.*k.^6.*exp(4.*k) + ...
            i.*AB.*S.*k.^6 + 8.*AB.*k.^8.*exp(2.*k) + 2.*AB.*k.^6.*exp(4.*k) + ...
            12.*AB.*k.^6.*exp(2.*k) + 2.*AB.*k.^6 + ...
            8.*i.*AB.*k.^5.*cotbeta.*exp(2.*k) - ...
            2.*i.*AB.*k.^4.*cotbeta.*exp(4.*k) + 2.*i.*AB.*k.^4.*cotbeta + ...
            4.*i.*AK.*S.*k.^3.*exp(2.*k) - i.*AK.*S.*k.^2.*exp(4.*k) + ...
            i.*AK.*S.*k.^2 + 8.*AK.*k.^4.*exp(2.*k) + 2.*AK.*k.^2.*exp(4.*k) + ...
            12.*AK.*k.^2.*exp(2.*k) + 2.*AK.*k.^2 + ...
            8.*i.*AK.*k.*cotbeta.*exp(2.*k) - 2.*i.*AK.*cotbeta.*exp(4.*k) + ...
            2.*i.*AK.*cotbeta + 4.*i.*AT.*S.*k.^5.*exp(2.*k) - ...
            i.*AT.*S.*k.^4.*exp(4.*k) + i.*AT.*S.*k.^4 + ...
            8.*AT.*k.^6.*exp(2.*k) + 2.*AT.*k.^4.*exp(4.*k) + ...
            12.*AT.*k.^4.*exp(2.*k) + 2.*AT.*k.^4 + ...
            8.*i.*AT.*k.^3.*cotbeta.*exp(2.*k) - ...
            2.*i.*AT.*k.^2.*cotbeta.*exp(4.*k) + 2.*i.*AT.*k.^2.*cotbeta - ...
            8.*i.*S.*k.^3.*cotbeta.*exp(2.*k) + 4.*S.*k.^3.*exp(4.*k) - ...
            4.*S.*k.^3 + 2.*i.*S.*k.^2.*cotbeta.*exp(4.*k) - ...
            2.*i.*S.*k.^2.*cotbeta - 16.*k.^4.*cotbeta.*exp(2.*k) + ...
            8.*i.*k.^3.*exp(4.*k) + 16.*i.*k.^3.*exp(2.*k) + 8.*i.*k.^3 - ...
            4.*k.^2.*cotbeta.*exp(4.*k) - 24.*k.^2.*cotbeta.*exp(2.*k) - ...
            4.*k.^2.*cotbeta - 16.*i.*k.*cotbeta.^2.*exp(2.*k) + ...
            8.*k.*cotbeta.*exp(4.*k) - 8.*k.*cotbeta + ...
            4.*i.*cotbeta.^2.*exp(4.*k) - ...
            4.*i.*cotbeta.^2)./(2.*(8.*AI.*k.^6.*exp(2.*k) + ...
            2.*AI.*k.^4.*exp(4.*k) + 4.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^4)) + ...
            9.*(8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).*(8.*AB.*k.^7.*exp(2.*k) + 2.*AB.*k.^5.*exp(4.*k) + ...
            4.*AB.*k.^5.*exp(2.*k) + 2.*AB.*k.^5 - 4.*AD.*S.*k.^3.*exp(2.*k) + ...
            AD.*S.*k.^2.*exp(4.*k) - AD.*S.*k.^2 + 8.*i.*AD.*k.^4.*exp(2.*k) + ...
            2.*i.*AD.*k.^2.*exp(4.*k) + 12.*i.*AD.*k.^2.*exp(2.*k) + ...
            2.*i.*AD.*k.^2 - 8.*AD.*k.*cotbeta.*exp(2.*k) + ...
            2.*AD.*cotbeta.*exp(4.*k) - 2.*AD.*cotbeta + ...
            8.*AK.*k.^3.*exp(2.*k) + 2.*AK.*k.*exp(4.*k) + 4.*AK.*k.*exp(2.*k) ...
            + 2.*AK.*k + 8.*AT.*k.^5.*exp(2.*k) + 2.*AT.*k.^3.*exp(4.*k) + ...
            4.*AT.*k.^3.*exp(2.*k) + 2.*AT.*k.^3 + 2.*S.*k.^3.*exp(4.*k) + ...
            4.*S.*k.^3.*exp(2.*k) + 2.*S.*k.^3 - 16.*i.*k.^4.*exp(2.*k) - ...
            16.*k.^3.*cotbeta.*exp(2.*k) + 4.*i.*k.^3.*exp(4.*k) - 4.*i.*k.^3 ...
            + 8.*i.*k.^2.*exp(4.*k) + 8.*i.*k.^2)./(2.*(8.*AI.*k.^4.*exp(2.*k) ...
            + 2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2).*(8.*AI.*k.^5.*exp(2.*k) + 2.*AI.*k.^3.*exp(4.*k) + ...
            4.*AI.*k.^3.*exp(2.*k) + 2.*AI.*k.^3)) + ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2).^3./(8.*AI.*k.^4.*exp(2.*k) + 2.*AI.*k.^2.*exp(4.*k) ...
            + 4.*AI.*k.^2.*exp(2.*k) + 2.*AI.*k.^2).^3).^(1./3)./3 - ...
            (8.*i.*AD.*k.^3.*exp(2.*k) + 2.*i.*AD.*k.*exp(4.*k) + ...
            4.*i.*AD.*k.*exp(2.*k) + 2.*i.*AD.*k - ...
            4.*i.*AI.*S.*k.^3.*exp(2.*k) + i.*AI.*S.*k.^2.*exp(4.*k) - ...
            i.*AI.*S.*k.^2 - 8.*AI.*k.^4.*exp(2.*k) - 2.*AI.*k.^2.*exp(4.*k) - ...
            12.*AI.*k.^2.*exp(2.*k) - 2.*AI.*k.^2 - ...
            8.*i.*AI.*k.*cotbeta.*exp(2.*k) + 2.*i.*AI.*cotbeta.*exp(4.*k) - ...
            2.*i.*AI.*cotbeta - 16.*i.*k.^3.*exp(2.*k) + 4.*i.*k.^2.*exp(4.*k) ...
            - 4.*i.*k.^2)./(3.*(8.*AI.*k.^4.*exp(2.*k) + ...
            2.*AI.*k.^2.*exp(4.*k) + 4.*AI.*k.^2.*exp(2.*k) + ...
            2.*AI.*k.^2))];
    end
    
    for j = 1:size(out,1)
        [~,index] = sort(imag(out(j,:)), 2, 'descend');
        out(j,:) = out(j,index);
    end
end
